config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :powers
  resources :races
  resources :kinds
  resources :civilizations
  resources :rarities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root "cards#index"

end

app/models/power.rb
class Power < ApplicationRecord
    has_many :cards
end

app/controllers/powers_controller.rb
class PowersController < ApplicationController
  before_action :set_power, only: [:show, :edit, :update, :destroy]

  # GET /powers
  # GET /powers.json
  def index
    @powers = Power.all
  end

  # GET /powers/1
  # GET /powers/1.json
  def show
  end

  # GET /powers/new
  def new
    @power = Power.new
  end

  # GET /powers/1/edit
  def edit
  end

  # POST /powers
  # POST /powers.json
  def create
    @power = Power.new(power_params)

    respond_to do |format|
      if @power.save
        format.html { redirect_to @power, notice: 'Power was successfully created.' }
        format.json { render :show, status: :created, location: @power }
      else
        format.html { render :new }
        format.json { render json: @power.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /powers/1
  # PATCH/PUT /powers/1.json
  def update
    respond_to do |format|
      if @power.update(power_params)
        format.html { redirect_to @power, notice: 'Power was successfully updated.' }
        format.json { render :show, status: :ok, location: @power }
      else
        format.html { render :edit }
        format.json { render json: @power.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /powers/1
  # DELETE /powers/1.json
  def destroy
    @power.destroy
    respond_to do |format|
      format.html { redirect_to powers_url, notice: 'Power was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_power
      @power = Power.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def power_params
      params.require(:power).permit(:value)
    end
end

app/helpers/powers_helper.rb
module PowersHelper
end

app/views/powers/_form.html.erb
<%= form_for(power) do |f| %>
  <% if power.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(power.errors.count, "error") %> prohibited this power from being saved:</h2>

      <ul>
      <% power.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %>
    <%= f.number_field :value %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/powers/edit.html.erb
<h1>Editing Power</h1>

<%= render 'form', power: @power %>

<%= link_to 'Show', @power %> |
<%= link_to 'Back', powers_path %>

app/views/powers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Powers</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @powers.each do |power| %>
      <tr>
        <td><%= power.value %></td>
        <td><%= link_to 'Show', power %></td>
        <td><%= link_to 'Edit', edit_power_path(power) %></td>
        <td><%= link_to 'Destroy', power, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Power', new_power_path %>

app/views/powers/new.html.erb
<h1>New Power</h1>

<%= render 'form', power: @power %>

<%= link_to 'Back', powers_path %>

app/views/powers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @power.value %>
</p>

<%= link_to 'Edit', edit_power_path(@power) %> |
<%= link_to 'Back', powers_path %>