config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :powers
  resources :races
  resources :kinds
  resources :civilizations
  resources :rarities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    root "cards#index"

end

app/models/rarity.rb
class Rarity < ApplicationRecord
  has_many :cards
end

app/controllers/rarities_controller.rb
class RaritiesController < ApplicationController
  before_action :set_rarity, only: [:show, :edit, :update, :destroy]

  # GET /rarities
  # GET /rarities.json
  def index
    @rarities = Rarity.all
  end

  # GET /rarities/1
  # GET /rarities/1.json
  def show
  end

  # GET /rarities/new
  def new
    @rarity = Rarity.new
  end

  # GET /rarities/1/edit
  def edit
  end

  # POST /rarities
  # POST /rarities.json
  def create
    @rarity = Rarity.new(rarity_params)

    respond_to do |format|
      if @rarity.save
        format.html { redirect_to @rarity, notice: 'Rarity was successfully created.' }
        format.json { render :show, status: :created, location: @rarity }
      else
        format.html { render :new }
        format.json { render json: @rarity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rarities/1
  # PATCH/PUT /rarities/1.json
  def update
    respond_to do |format|
      if @rarity.update(rarity_params)
        format.html { redirect_to @rarity, notice: 'Rarity was successfully updated.' }
        format.json { render :show, status: :ok, location: @rarity }
      else
        format.html { render :edit }
        format.json { render json: @rarity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rarities/1
  # DELETE /rarities/1.json
  def destroy
    @rarity.destroy
    respond_to do |format|
      format.html { redirect_to rarities_url, notice: 'Rarity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rarity
      @rarity = Rarity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rarity_params
      params.require(:rarity).permit(:name)
    end
end

app/helpers/rarities_helper.rb
module RaritiesHelper
end

app/views/rarities/_form.html.erb
<%= form_for(rarity) do |f| %>
  <% if rarity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rarity.errors.count, "error") %> prohibited this rarity from being saved:</h2>

      <ul>
      <% rarity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rarities/edit.html.erb
<h1>Editing Rarity</h1>

<%= render 'form', rarity: @rarity %>

<%= link_to 'Show', @rarity %> |
<%= link_to 'Back', rarities_path %>

app/views/rarities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rarities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rarities.each do |rarity| %>
      <tr>
        <td><%= rarity.name %></td>
        <td><%= link_to 'Show', rarity %></td>
        <td><%= link_to 'Edit', edit_rarity_path(rarity) %></td>
        <td><%= link_to 'Destroy', rarity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rarity', new_rarity_path %>

app/views/rarities/new.html.erb
<h1>New Rarity</h1>

<%= render 'form', rarity: @rarity %>

<%= link_to 'Back', rarities_path %>

app/views/rarities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rarity.name %>
</p>

<%= link_to 'Edit', edit_rarity_path(@rarity) %> |
<%= link_to 'Back', rarities_path %>